### ISSUE TITLE
main module import raises ImportError in Python 3

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/shellescape#1]
report by @chrisidefix : 

``` python
import shellescape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/shellescape/__init__.py", line 4, in <module>
    from main import quote
ImportError: No module named 'main'
```

**Comment by chrissimpkins** [comment]
fixed in v3.4.1
